### ISSUE TITLE
override form class

### ISSUE THREAD

**Issue by ivang76** [ABWebDevelopers/oc-forms-plugin#36]
Hi there,
thank you for this great plugin!

I noticed that the override form class is not used in the rendered form... even if I force a new class for the form, in the html code there is still the default "custom-form" value.

With the event "abweb.forms.beforeRenderPartial" I see the custom value is set in the attributes, but then is not used when the form is rendered in the page.

**Comment by Hessel91** [comment]
same issue here. Did you find a workaround or fix?

**Comment by Hessel91** [comment]
hard coded it in : abwebdevelopers/forms/classes/HtmlGenerator.php line 111. 
however this is not the solution, I have to prevent updates now. Is there any support from the author?

**Comment by bradietilley** [comment]
Please see `v1.6.0` which will now use the form's "Form Class" in the rendered HTML. Can't believe this was overlooked (never needed it personally). Due to backwards-compatibility I've retained the original CSS class there (`custom-form`) so you _may_ have to increase your specificity of your CSS rules in order to target the form correctly.
