### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by ivang76** [ABWebDevelopers/oc-forms-plugin#37]
I tested and worked with this plugin without problem on an old installation in my local dev.
Now I'm trying to install on a remote server, I had to update OctoberCms to go on, but the installation fails:

**`SQLSTATE[42000]: Syntax error or access violation: 1142 REFERENCES command denied to user 'ivan'@'localhost' for table 'abwebdevelopers_forms_fields' (SQL: alter table `abwebdevelopers_forms_forms` add constraint `abwebdevelopers_forms_forms_auto_reply_name_field_id_foreign` foreign key (`auto_reply_name_field_id`) references `abwebdevelopers_forms_fields` (`id`) on delete cascade)" on line 664 of /var/opt/www/usilu_institutes/docs/vendor/laravel/framework/src/Illuminate/Database/Connection.php`**

I know you are busy with WinterCms but please let me know somthing about this, thank you

**Comment by bradietilley** [comment]
It sounds like the initial migration that adds Foreign Key Constraints is failing due to... permissions(?). Well, I don't like FKCs at all as they give more headaches than purpose.

As such - see v1.5.0... I have removed all traces of FKCs from historic migrations (initialise database v1.0.0). I understand that this update is changing the plugin's history and thus would be typically frowned upon, however I have also tested a few scenarios and all appears to work very well. Fresh installs work perfectly (i.e. don't create any FKCs, and don't fail on v1.2.1 when they're removed), and also, updating from a version < 1.2.1 (where you would already have FKCs in the database) also works well - the FKCs are safely dropped.

I'm hoping that the v1.5.0 will resolve the issue you're experiencing. Let me know if you continue to experience this issue.

> I know you are busy with WinterCms

Not me but Ben is busy yeah :)

**Comment by ivang76** [comment]
Thank you @bradietilley for your fix and answer.
I installed manually via git the v1.5 and then run a  `php artisan plugin:refresh ABWebDevelopers.Forms`

no error during installation and no error with migrations, that's cool, but now when I open a page (CMS or Static Pages) that contains a custom form, I get this error:
**Class 'YeTii\HtmlElement\Elements\HtmlDiv' not found**

**Comment by bradietilley** [comment]
@ivang76 That suggests that the composer dependencies aren't installing correctly. Have you run `composer install`?

These classes, albeit powerful, are restrictive - I see that now. I want to release v2 of this plugin that has options for the engine - PHP classes (as currently used), Twig (for those who want it), and maybe Blade (for those who prefer it over Twig).... but I haven't got the time

**Comment by ivang76** [comment]
ok thanks, I just cleaned and reforced a new composer install and now it's working.
Yes, that features on v2 could be really interesting indeed.

About this fixed version, are you planning to release also via october market (and winter probably?)?

**Comment by bradietilley** [comment]
@ivang76 We'd likely target both CMS platforms, however currently I'm heavily bogged down so don't see myself doing this anytime soon (unfortunately).
