### ISSUE TITLE
Checkbox and select values

### ISSUE THREAD

**Issue by erwanregnier** [ABWebDevelopers/oc-forms-plugin#4]
Actually it's not possible to choose a different label and value for select and checkbox/radio fields options.
Will it be available in the next version?
thanks

**Comment by bradietilley** [comment]
Yeah, unfortunately my quick implementation of "options" is seriously lacking, in more ways than one.

Next version will see a better options facility, as well as the ability to add custom attributes, a refactor/redesign of the templating of the form + fields using an HTML element generator library (because Twig is meh), and of course a few extra field types. 

Been really busy lately but hoping to get another release out by the end of the week.
